name: Auto Update IPTV

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update Playlist
        run: |
          curl -L "https://raw.githubusercontent.com/ahmedstore75/StreamBangla/main/BDIX-Playlist.m3u" -o BDIX-Playlist.m3u

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email actions@github.com

          git add .
          git commit -m "Auto Update" || exit 0
          git push
