name: Auto Update IPTV

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Latest Playlist
        run: |
          curl -L "https://raw.githubusercontent.com/ahmedstore75/Iptvbdlive/main/mixiptvchannel.m3u" -o BDIX-Playlist.m3u

      - name: Commit Changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add BDIX-Playlist.m3u
          git commit -m "Auto update playlist" || exit 0
          git push
