name: Auto Update IPTV

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download latest M3U
        run: |
          curl -L "https://raw.githubusercontent.com/ahmedstore75/Iptvbdlive/main/mixiptvchannel.m3u" -o BDIX-Playlist.m3u

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add BDIX-Playlist.m3u

          git diff --cached --quiet || git commit -m "Auto update playlist"

          git push
